domains:
  - florimond.dev
  - www.florimond.dev
  - blog.florimond.dev
  - florimondmanca.com
  - blog.florimondmanca.com

letsencrypt_enabled: true
webmentions_url: https://webmention.io/florimond.dev/webmention
