- name: Install build requirements
  become: true
  package:
    name: "{{ pyenv_build_requirements }}"
    state: present
    update_cache: true

- name: Clone pyenv
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: "{{ pyenv_root }}"
    version: "{{ pyenv_version }}"
