- name: Collect path to pyenv binary
  set_fact:
    pyenv_bin_path: "{{ pyenv_root }}/bin/pyenv"
  when: pyenv_bin_path is undefined

- name: Create .pyenvrc
  template:
    src: ".pyenvrc.j2"
    dest: "{{ pyenv_root }}/.pyenvrc"
    mode: "0644"
