- name: Provision-time setup
  tags: provision
  block:
    - name: Ensure a locale is set
      locale_gen:
        name: en_GB.UTF-8
        state: present
      become: true

    - name: Ensure apt is up to date
      apt: update_cache=true
      become: true

    - name: Ensure common packages are installed
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - software-properties-common
        - curl
        - git
        - make
        - htop
        - gnupg2
        - gettext
      become: true

    - name: Ensure pyenv is configured
      import_role:
        name: pyenv

    - name: Ensure Nginx is installed
      apt: name=nginx state=latest
      become: true

    - name: Ensure Certbot is configured
      import_role:
        name: certbot

    - name: Ensure supervisor is installed
      apt: name=supervisor state=latest
      become: true

- name: Deploy-time setup
  tags: deploy
  block:
  - name: Ensure nginx is running
    service: name=nginx state=started
    become: true

  - name: Ensure supervisor is running
    service: name=supervisor state=started enabled=yes
    become: true
