- name: Deploy
  tags: deploy
  block:
  - name: Sync nginx
    import_tasks: nginx.yml

  - name: Sync git
    import_tasks: git.yml

  - name: Sync dotenv
    import_tasks: dotenv.yml

  - name: Sync install
    import_tasks: install.yml

  - name: Sync build
    import_tasks: build.yml

  - name: Sync supervisor
    import_tasks: supervisor.yml
