#! /bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

export SOURCE_FILES="server tests"

set -x

${PREFIX}black --check --diff $SOURCE_FILES
${PREFIX}flake8 $SOURCE_FILES
${PREFIX}mypy $SOURCE_FILES
${PREFIX}isort --check --diff $SOURCE_FILES
${PREFIX}python -m server.tools.mdformat --check
${PREFIX}python -m server.tools.imgoptimize --check
${PREFIX}python -m server.tools.imgsize
