#!/bin/sh -e -x

if [ -d 'src/www/blog/site/.vuepress/dist' ] ; then
    rm -r src/www/blog/site/.vuepress/dist
fi

if [ -d 'dist' ] ; then
    rm -r dist
fi

if [ -d 'build' ] ; then
    rm -r build
fi

find src -type f -name "*.py[co]" -delete
find src -type d -name __pycache__ -delete
