#!/bin/sh -e -x

if [ -d 'blog/site/.vuepress/dist' ] ; then
    rm -r blog/site/.vuepress/dist
fi

if [ -d 'dist' ] ; then
    rm -r dist
fi

if [ -d 'build' ] ; then
    rm -r build
fi

find apps -type f -name "*.py[co]" -delete
find apps -type d -name __pycache__ -delete
