#!/bin/bash

if [ -z $CI ]; then
  python -m venv venv
fi

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

${PREFIX}pip install -r requirements.txt

if [[ "$@" = *"--no-node"* ]]; then
  echo "--no-node: Skipping yarn install"
else
  yarn install
fi
