#!/bin/bash

note() { echo "-----> $1"; }

if [ -z $CI ]; then
  note "Create virtual environment"
  python -m venv venv

  export PREFIX="venv/bin/"

  note "Upgrade pip"
  ${PREFIX}pip install -U pip

  if ! [ -f .env ]; then
    note "Add .env"
    echo "# App configuration." >> .env
    echo "DEBUG=true" >> .env
    echo 'DD_TAGS="env:local"' >> .env
    echo "# Heroku CLI configuration." >> .env
    echo "PYTHONUNBUFFERED=true" >> .env
    echo "PORT=8000" >> .env
  fi
else
  note "CI pipeline detected: will use system executables"
  export PREFIX=""
fi

if [[ "$@" = *"--update"* ]]; then
  note "Update pip dependencies"
  rm -f requirements.txt
  ${PREFIX}pip install -U -r requirements.in
  ${PREFIX}pip freeze > requirements.txt
else
  note "Install pip dependencies"
  ${PREFIX}pip install -U -r requirements.txt
fi

if ! [[ "$@" = *"--no-node"* ]]; then
  note "Install yarn dependencies"
  yarn install
fi
