#!/bin/bash

note() { echo "-----> $@"; }
ci_detected() { note "CI pipeline detected: $@"; }

if [ -z $CI ]; then
  export PREFIX="venv/bin/"

  if [ ! -d venv ]; then
    note "Create virtual environment"
    python -m venv venv

    note "Upgrade pip"
    ${PREFIX}pip install -U pip
  fi

  if ! [ -f .env ]; then
    note "Add .env"
    echo "# App configuration." >> .env
    echo "DEBUG=true" >> .env
    echo 'DD_TAGS="env:local"' >> .env
    echo "# Heroku CLI configuration." >> .env
    echo "PYTHONUNBUFFERED=true" >> .env
    echo "PORT=8000" >> .env
  fi
else
  ci_detected "Using system Python executables"
  export PREFIX=""
fi

# Prevent falling back to legacy 'setup.py install' for wheels.
note "Upgrade package 'wheel'"
${PREFIX}pip install -U wheel

note "Install pip dependencies"
${PREFIX}pip install -r requirements.txt

if [ -z $CI ]; then
  note "Install yarn dependencies"
  yarn install
else
  ci_detected "Skipping yarn dependencies"
fi
