#! /bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

export SOURCE_FILES="src tests"

set -x

${PREFIX}autoflake --in-place --recursive $SOURCE_FILES
${PREFIX}seed-isort-config --application-directories=src
${PREFIX}isort --project=www --recursive $SOURCE_FILES
${PREIFX}black --target-version=py37 $SOURCE_FILES
