#!/bin/sh -e

export PREFIX=""
if [ -d "venv" ] ; then
    export PREFIX="venv/bin/"
fi

LOCALE_DIR="locale"
BASE_FILE="$LOCALE_DIR/base.pot"
INIT_MARKER_FILE="$LOCALE_DIR/.init"

set -x

mkdir -p $LOCALE_DIR

${PREFIX}pybabel extract -F babel.cfg -o $BASE_FILE ./server/

if [ -f $INIT_MARKER_FILE ]; then
    ${PREFIX}pybabel update -i $BASE_FILE -d $LOCALE_DIR
else
    ${PREFIX}pybabel init -l fr_FR -i $BASE_FILE -d $LOCALE_DIR
    touch $INIT_MARKER_FILE
fi
