#! /bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

set -x

${PREFIX}python -m sitemaps server:app --asgi -H 'https://florimond.dev' -I 'static/' -O 'server/static/sitemap.xml' "$@"
