#! /bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

set -x

${PREFIX}python -m sitemaps --asgi server:app -I 'static/' -I 'feed.rss' -o 'server/static/sitemap.xml' https://florimond.dev
