#! /bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

set -x

export SITEMAP="server/static/sitemap.xml"
export OPTIONS="server:app --base-url https://florimond.dev -I static/ -I feed.rss"

if [ "$1" == "--check" ]; then
    cat $SITEMAP | ${PREFIX}python -m asgi_sitemaps $OPTIONS --check
else
    ${PREFIX}python -m asgi_sitemaps $OPTIONS > $SITEMAP
fi
